---
# ParseCommand replaces these keys with the respective values
synonyms:
  # Directions
  e: east
  n: north
  s: south
  w: west

  # Verbs
  boogie: dance
  examine: describe
  grab: get
  how: what
  inspect: describe
  inv: inventory
  moonwalk: dance
  move: go
  place: put
  run: go
  take: get
  walk: go
  waltz: dance
  when: what
  where: what
  who: what
  why: what

# ParseCommand ignores these words entirely
ignored_words:
- a
- the

# Any of the following keys found in the first word position
# will result in the associated value being added as the verb
implicit_verbs:
  east: go
  north: go
  south: go
  west: go
