---
synonyms:
  # Directions
  e: east
  n: north
  s: south
  w: west

  # Verbs
  boogie: dance
  examine: describe
  grab: get
  how: what
  inspect: describe
  inv: inventory
  moonwalk: dance
  move: go
  place: put
  run: go
  take: get
  walk: go
  waltz: dance
  when: what
  where: what
  who: what
  why: what

ignored_words:
- a
- the
