---
# Words matching these keys will be replaced with the respective values
synonyms:
  # Directions
  e: east
  n: north
  s: south
  w: west

  # Verbs
  boogie: dance
  examine: describe
  grab: get
  how: what
  inspect: describe
  inv: inventory
  moonwalk: dance
  move: go
  place: put
  run: go
  take: get
  walk: go
  waltz: dance
  when: what
  where: what
  who: what
  why: what

  # Nouns
  branches: trees
  grove: trees
  forest: trees

  # Prepositions
  into: in
  onto: "on"

# These words will be ignored entirely
ignored_words:
- a
- the

# If a word matching any of the following keys is found in the
# first word (verb) position, the associated value will be added in the
# first word position.
implicit_verbs:
  east: go
  north: go
  south: go
  west: go
