---
# Directions
e: go east
east: go east
n: go north
north: go north
s: go south
south: go south
w: go west
west: go west

# Verbs
boogie: dance
examine: describe
grab: get
how: what
inspect: describe
inv: inventory
moonwalk: dance
move: go
place: put
run: go
take: get
walk: go
waltz: dance
when: what
where: what
who: what
why: what
