---
# Directions
e: go east
east: go east
n: go north
north: go north
s: go south
south: go south
w: go west
west: go west

# Verbs
examine: describe
grab: get
inspect: describe
inv: inventory
move: go
run: go
take: get
walk: go
