---
adventure: lost_desert

player:
  location_id: salt_flats
  health: 10

messages:
  welcome: |+
    This is the Lost Desert Adventure.
    Type 'help' for instructions.
  won: |+
    Congratulations, you won!
  lost: |+
    You have died. Please try again.

locations:
- id: salt_flats
  name: salt flats
  description:
    general: A vast, flat landscape of dry, cracked tiles. Only the smallest breeze can be felt in the hot sun.
    tiles: The tiles appear to be made of dried salt, created by the drying and cracking of the flat.
    eat: mmm... salty!
  movements:
    east:
      location_id: great_dunes
    south:
      location_id: stone_ruins
- id: great_dunes
  name: great dunes
  description:
    general: Massive sandy dunes loom before you, shifting slightly in the wind.
    dunes: The dunes are all very tall, but one of them in the middle towers over the others.
    eat: If you want a mouthful of sand, then sure.
  movements:
    south:
      location_id: mossy_temple
    west:
      location_id: salt_flats
    up:
      location_id: top_of_dune
- id: top_of_dune
  name: top of great dune
  description:
    general: You trek to the top of the sand dune, shielding your eyes from the blazing sun. You notice
    cobra: Its forked tongue slithers in and out of bared fangs. A loud hiss signals it doesn't take visitors very kindly...
  movements:
    down:
      location_id: great_dunes
- id: stone_ruins
  name: stone ruins
  description:
    general: Mossy boulders and pillars surround you, some of them carved with engravings.
    stone: As you look closer, you see that the stone is covered in markings, resembling some sort of ancient writing.
    engravings: The markings resemble humans bowing down and giving offerings to snake-like creatures, which they seemed to worship.
  movements:
    north:
      location_id: salt_flats
    east:
      location_id: mossy_temple
    west:
      location_id: willow_forest
- id: mossy_temple
  name: ruinous temple
  description:
    general: A large, stone structure resembling some sort of ancient temple.
    temple: The building is falling apart, and only one front pillar remains intact. You also notice a glass bottle sitting in front of the temple.
    pillar: Cracks run through the carved stone, and it seems like the pillar won't hold for much longer. You can make out rough pictures of snakes embellished in the stone.
    bottle: Interestingly enough, the bottle is engraved with the same riddle the stone had, but contains a new verse as well.
  movements:
    north:
      location_id: great_dunes
    west:
      location_id: stone_ruins
- id: willow_forest
  name: weeping willow forest
  description:
    general: A peaceful grove of blossoming willow trees lay before you, swaying in the cool breeze.
    trees: The trees are all closely packed together, and a pair of snow boots lay nestled in one of the tree's thick roots.
    boots: The old boots are tattered and worn, but still look usable for good traction in snowy terrain.
  movements:
    north:
      location_id: snowy_mountains
    east:
      location_id: stone_ruins
- id: snowy_mountains
  name: snowy mountains
  description:
    general: High, icy peaks tower above the clouds, and freezing wind pelts you from all directions.
    peaks: Higher than any other mountains you've seen before, these peaks are truly a magnificent sight. You also notice a chest up above you on a small ledge sticking out from the mountainside.
    chest: The chest looks very battered and wet, but its thick oak casing and heavy metal lock seem to be standing up to the wind very well.
  movements:
    south:
      location_id: willow_forest

items:
  - id: tablet
    alternate_names:
      - stone
    name: ancient stone tablet
    description: an old, square shaped stone, covered in ancient writing.
    location_key: stone_ruins
    size: 999
    text: Cobra venom is required to fulfill the prophecy we desire.

characters:
  - id: cobra
    name: large cobra
    description: a large cobra, protectively guarding its nest.
    location_key: top_of_dune
    visible: false
    reactions:
      get: You reach out to grab the serpent, but it recoils and spits venom at you.
      kill: You strike, but the cobra strikes first. Fangs bared, it bites you viciously with venomous teeth.
      put: I wouldn't recommend trying to put a snake somewhere.
      eat: It would rather eat you.
